### ISSUE TITLE
How about the other way around was well?

### ISSUE THREAD

**Issue by codingcatgirl** [rytilahti/homeassistant-mpris-bridge#1]
This is such an exciting idea! However, what about the other way around?

When i play a youtube video on chromium, it seems to also expose it's controls via MPRIS. I'd love if i could access those controls via home assistant as well.

**Comment by rytilahti** [comment]
Tbh, I haven't looked into that and I'm not personally interested in adding such, but the repo is open for PRs! Just something I noticed at some point: the exposed browser instances contained an unique id as a suffix (maybe a pid?), so I'm not sure what would be the best way to handle that to avoid dangling, stale entities on homeassistant.

**Comment by LukaszMoskala** [comment]
So I was looking for reverse option as well and I found this: https://pypi.org/project/hassmpris-agent/ and it does what I want it to do.

@rytilahti I think it would be good idea to mention this in readme

**Comment by rytilahti** [comment]
Nice find! Feel free to create a PR for the readme.
